# Generated by Django 6.0.6 on 2026-06-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='fortaleza')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='descripción')),
                ('icon_name', models.CharField(blank=True, max_length=80, verbose_name='icono')),
            ],
            options={
                'verbose_name': 'fortaleza profesional',
                'verbose_name_plural': 'fortalezas profesionales',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio'),
        ),
    ]
